http_path = "../"
css_dir = "../css/"
sass_dir = "."
images_dir = "../images/"
javascripts_dir = "../js/"
# output_style = :compressed
output_style = :expanded
relative_assets= true
line_comments = false